name: Tutorial
authors: [YourName]
description: A tutorial on building spigot server
version: 1.0
main: tutorial.Main
commands:
  tutorial:
    description: This is a tutorial command!
    usage: /tutorial
