name: Tutorial
authors: [YourName]
description: A tutorial on building spigot server
version: 1.0
main: tutorial.Main
commands:
  helloworld:
    description: This is a tutorial command!
    usage: /helloworld
  config:
    description: This shows the data in the config!
    usage: /config